### ISSUE TITLE
[Fluent] Mappings: Indexes and Unique Constraints

### ISSUE THREAD

**Issue by guiwoda** [laravel-doctrine/docs#25]
Explain how to add custom indexes and unique constraints to single fields and multiple fields.

**Comment by hiddeco** [comment]
@guiwoda and let me handle this one :smile:

**Comment by guiwoda** [comment]
@hiddeco I covered this topic in #38

**Comment by guiwoda** [comment]
Closing this issue, as it was fixed in #38.
