### ISSUE TITLE
Update documentation process for install fluent

### ISSUE THREAD

**Issue by artmadeit** [laravel-doctrine/docs#54]
In the documentation in http://www.laraveldoctrine.org/docs/1.1/fluent/entities and also in this docs..
say:

> If you're using Laravel and Doctrine through the laravel-doctrine/orm package, then all you need to do here is add the ScientistMapping class reference to your config file

But it isn't anymore, I saw that in laravel-doctrine/orm doesn't have fluent, now you need to install it apart.
Sorry for my bad English I'm from Perú

**Comment by hiddeco** [comment]
No, the documentation is correct. It describes how you configure Fluent while using Laravel Doctrine instead of standalone mode.

**Comment by patrickbrouwers** [comment]
You'll have to install the package with composer:

```
composer require laravel-doctrine/fluent
```

**Comment by artmadeit** [comment]
I added that because as @patrickbrouwers  said you need to install the package, but the documentation doesn't said that. That was all...

**Comment by patrickbrouwers** [comment]
For some reason the installation section indeed misses that information, however the github readme has the information. Will add it to the docs. Thanks for noticing.
