### ISSUE TITLE
Wrong syntax for custom cache driver

### ISSUE THREAD

**Issue by k0ka** [laravel-doctrine/docs#92]
https://github.com/laravel-doctrine/docs/blob/1.5/orm/caching.md

This syntax is deprecated
`$cache->extend('memcache', function(Application $app)`

and should be replaced by
`$cache->extend('memcache', function(array $settings, Application $app)`

**Comment by vv12131415** [comment]
@k0ka can you please make a PR?

**Comment by k0ka** [comment]
Sure.
https://github.com/laravel-doctrine/docs/pull/93

It may be applied to all branches. Even version 1.0 already has this invocation syntax
https://github.com/laravel-doctrine/orm/blob/1.0/src/Configuration/Manager.php#L111

**Comment by vv12131415** [comment]
Thanks @k0ka
